### ISSUE TITLE
Is this connector also available for query？

### ISSUE THREAD

**Issue by liaooo** [StarRocks/flink-connector-starrocks#4]
We all know that flink-connector-mysql is compatible with query starrocks, is this new connector also compatible

**Comment by liaooo** [comment]
I checked the code, StarRocksDynamicTableSinkFactory only implements DynamicTableSinkFactory, so this connector only supports the sink.

**Comment by hffariel** [comment]
> I checked the code, StarRocksDynamicTableSinkFactory only implements DynamicTableSinkFactory, so this connector only supports the sink.

We've already had a `SourceFunction` under testing, but still got some problems to deal with before the final release.
Feel free to contact us for a snapshot.jar package on our [forum](https://forum.starrocks.com) if you wanna try it out.

**Comment by wzq2468101** [comment]
具体错误信息：
`
[INFO] 2022-01-25 15:48:51.016  - [taskAppId=TASK-619-46995-141369]:[129] -  -> java.lang.NoSuchFieldError: INSTANCE
		at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
		at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:964)
		at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56)
		at com.starrocks.connector.flink.manager.StarRocksQueryPlanVisitor.getQueryPlan(StarRocksQueryPlanVisitor.java:110)
		at com.starrocks.connector.flink.manager.StarRocksQueryPlanVisitor.getQueryInfo(StarRocksQueryPlanVisitor.java:63)
		at com.starrocks.connector.flink.table.source.StarRocksSourceCommonFunc.getQueryInfo(StarRocksSourceCommonFunc.java:206)
		at com.starrocks.connector.flink.table.source.StarRocksDynamicSourceFunction.<init>(StarRocksDynamicSourceFunction.java:83)
		at com.starrocks.connector.flink.table.source.StarRocksDynamicTableSource.getScanRuntimeProvider(StarRocksDynamicTableSource.java:66)
		at org.apache.flink.table.planner.connectors.DynamicSourceUtils.validateScanSource(DynamicSourceUtils.java:458)
		at org.apache.flink.table.planner.connectors.DynamicSourceUtils.prepareDynamicSource(DynamicSourceUtils.java:166)
		at org.apache.flink.table.planner.connectors.DynamicSourceUtils.convertSourceToRel(DynamicSourceUtils.java:124)
		at org.apache.flink.table.planner.plan.schema.CatalogSourceTable.toRel(CatalogSourceTable.java:85)
		at org.apache.calcite.sql2rel.SqlToRelConverter.toRel(SqlToRelConverter.java:3585)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:2507)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2144)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2093)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertFrom(SqlToRelConverter.java:2050)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:663)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:644)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3438)
		at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:570)
		at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$rel(FlinkPlannerImpl.scala:169)
		at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.rel(FlinkPlannerImpl.scala:161)
		at org.apache.flink.table.planner.operations.SqlToOperationConverter.toQueryOperation(SqlToOperationConverter.java:989)
		at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlQuery(SqlToOperationConverter.java:958)
		at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:283)
		at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:603)
		at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:272)
		at org.apache.flink.table.planner.delegation.ParserImpl.parse(ParserImpl.java:101)
		at org.apache.flink.table.api.internal.StatementSetImpl.addInsertSql(StatementSetImpl.java:51)
		at com.baishancloud.log.core.FlinkApplication.insertStatement(FlinkApplication.java:301)
		at com.baishancloud.log.core.FlinkApplication.executeAllSql(FlinkApplication.java:144)
		at com.baishancloud.log.core.FlinkApplication.start(FlinkApplication.java:73)
		at com.baishancloud.log.SubmitClient.main(SubmitClient.java:30)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
		at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
		at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
		at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
		at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
		at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
		at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
		at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
		at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
`
flink sql：
`
CREATE TABLE `statis_http_detail` (
	`domain` int,
	`time_at_1min` string,
	`is_parent` tinyint,
	`http_code` smallint,
	`is_hit` tinyint,
	`is_abroad` tinyint,
	`is_https` tinyint,
	`is_ipv6` tinyint,
	`vendor` string,
	`time_at_5min` string,
	`time_at_1hour` string,
	`time_at_1day` string,
	`request` bigint,
	`traffic` bigint,
	`pv` bigint
) WITH (
	'connector' = 'starrocks',
	'scan-url' = '',
	'jdbc-url' = '',
	'database-name' = '',
	'table-name' = '',
	'username' = '',
	'password' = ''
)
;

---------------------------------------------------石家庄表---------------------------------------------------------
CREATE TABLE `statis_http_detail_removal` (
	`domain` int,
	`time_at_1min` string,
	`is_parent` tinyint,
	`http_code` smallint,
	`is_hit` tinyint,
	`is_abroad` tinyint,
	`is_https` tinyint,
	`is_ipv6` tinyint,
	`vendor` string,
	`time_at_5min` string,
	`time_at_1hour` string,
	`time_at_1day` string,
	`request` bigint,
	`traffic` bigint,
	`pv` bigint
) WITH (
	'connector' = 'starrocks',
	'jdbc-url' = '',
	'load-url' = '',
	'database-name' = '',
	'table-name' = '',
	'username' = '',
	'password' = '',
	'sink.buffer-flush.max-bytes' = '94371840',
	'sink.buffer-flush.max-rows' = '500000',
	'sink.buffer-flush.interval-ms' = '300000',
-- 	'sink.properties.column_separator' = '\\x01',
-- 	'sink.properties.row_delimiter' = '\\x02',
	'sink.max-retries' = '3'
)
;


---------------------------------------------------导入语句---------------------------------------------------------
insert into statis_http_detail_removal
select domain, time_at_1min, is_parent, http_code, is_hit, is_abroad, is_https, is_ipv6, vendor, time_at_5min, time_at_1hour, time_at_1day, request, traffic, pv
from statis_http_detail
where time_at_1min >= '2021-12-19 00:00:00' and time_at_1min < '2022-01-19 00:00:00'
;
`

flink sql 中填写的那些信息是没问题的，字段都是可以和原始的starRocks表对应上的。
自己打包dev分支的scala 2.12版本。
