### ISSUE TITLE
ClassNotFoundException: org.apache.flink.calcite.shaded.com.google.common.base.Preconditions

### ISSUE THREAD

**Issue by BigData-YC** [StarRocks/flink-connector-starrocks#74]
Caused by: java.lang.ClassNotFoundException: org.apache.flink.calcite.shaded.com.google.common.base.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

**Comment by hehuiyuan** [comment]
‘flink-table-planner’  has the dependency.

**Comment by hffariel** [comment]
Have replaced it with `org.apache.flink.util.Preconditions`. Feel free to check out the latest code.
